#!/bin/bash
#SBATCH -A TG-CCR140008
#SBATCH -J particle-gpu
#SBATCH -o particle-gpu.stdout
#SBATCH -n 1         
#SBATCH -p gpu
#SBATCH -t 00:10:00     
#SBATCH --mail-type=END
#SBATCH --mail-user=22jjf22@gmail.com

ibrun ./gpu -n 500 -o gpu.txt
./autocorrect -s gpu.txt
